### ISSUE TITLE
An Exception when installed

### ISSUE THREAD

**Issue by miss85246** [ahmednafies/sanic-pydantic#12]
Hello there, 
I tried to install sanic-pydantic today, but there were some mistakes.
I run this command:
```bash
pip install sanic-pydantic -i  https://pypi.douban.com/simple
```
and it's raise error:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 324, in run
    requirement_set = resolver.resolve(
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 33, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 503, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_internal/pyproject.py", line 75, in load_pyproject_toml
    pp_toml = toml.load(f)
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_vendor/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/home/connor/.virtualenvs/test/lib/python3.8/site-packages/pip/_vendor/toml/decoder.py", line 362, in loads
    raise TomlDecodeError("Unterminated string found."
pip._vendor.toml.decoder.TomlDecodeError: Unterminated string found. Reached end of file. (line 23 column 1 char 434)
```
my python version is `Python 3.8.5`
my linux version is `Linux version 4.18.0-147.5.1.el8_1.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)) #1 SMP Wed Feb 5 02:00:39 UTC 2020`
can you give me some help? thanks

**Comment by FrailLeon** [comment]
Hi, I got same problem too.  

How I fixed this :
1. clone this project into the root folder of your project.  
2. add `'''` at the end of file which named 'pyproject.toml'  
3. run `poetry add sanic-pydantic ./sanic-pydantic/` in the root folder of your project.  

![sanic-pydantic](https://user-images.githubusercontent.com/17675832/94359204-4249c980-00d8-11eb-9f57-c902d9a19799.png)

我也遇到了同样的问题。

解决方法：
1. clone这个repo到你的项目根目录
2. 把`'''`加到 pyproject.toml 这个文件的末尾
3. 在你项目的根目录执行 `poetry add sanic-pydantic ./sanic-pydantic/`   
你可能需要先装好`poetry`，或者用其他办法安装，比如`setup.py`  

更简单的：
`poetry add sanic-pydantic https://github.com/FrailLeon/sanic-pydantic`

**Comment by miss85246** [comment]
@FrailLeon Hi,  I think you might like this library better, `sanic-dantic`, It's support cfv and cbv, you can try it. click [here](https://github.com/miss85246/sanic-dantic)
