### ISSUE TITLE
pip install error on python3.8

### ISSUE THREAD

**Issue by Jenuce** [ahmednafies/sanic-pydantic#15]
$ pip install  sanic-pydantic
Collecting sanic-pydantic
  Using cached sanic-pydantic-1.2.0.tar.gz (3.4 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
    return any(self)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    super().__init__(
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 29, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 493, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_internal/pyproject.py", line 62, in load_pyproject_toml
    pp_toml = toml.load(f)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_vendor/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/Users/jenuce/my_cms/venv/lib/python3.8/site-packages/pip/_vendor/toml/decoder.py", line 362, in loads
    raise TomlDecodeError("Unterminated string found."
pip._vendor.toml.decoder.TomlDecodeError: Unterminated string found. Reached end of file. (line 23 column 1 char 434)

**Comment by ahmednafies** [comment]
will update the package and fix soon for python 3.8
